FROM node:16.17.0

WORKDIR /app

COPY ./front-end/package.json ./front-end/package.json
COPY ./@csl/components/package.json ./@csl/components/package.json
COPY ./@csl/interfaces/package.json ./@csl/interfaces/package.json
COPY ./@csl/functions/package.json ./@csl/functions/package.json
COPY ./package.json ./

RUN npm install

COPY ./front-end/src ./front-end/src
COPY ./@csl ./@csl


CMD ["npm", "run", "app", "front-end"]